trab2_abilio_pargles: FatAnalyser Class Reference
FatAnalyser Class Reference
Contem os metodos para analisar as particoes FAT12.
#include <FatAnalyser.h>
Public Member Functions
FatAnalyser (Parser *parse)
Inicializa os atributos da classe FatAnalyser com valores default.
void run ()
Executa o analisador de fat.
Private Member Functions
void verificarParticoesFat ()
1.1 Verificar FATs Verificar se as duas FATs são iguais – caso não sejam, imprimir uma lista de diferenças no seguinte formato, com uma linha para cada diferença:
void imprimiListaDeBlocosLivres ()
1.2 Imprimir lista de blocos livres Imprime os índices de todos os blocos que estão livres (ou seja, não são apontados pela FAT) em uma única linha.
void imprimirListaDeBlocosComDados ()
1.3 Imprimir lista de blocos livres com dados Imprime os índices de todos os blocos que estão livres e que tem conteúdo diferente de zeros, em uma única linha.
void lerBloco (int bloco)
1.4 Ler um determinado bloco Parâmetro na linha de comando: -lb <numero do="" bloco>=""> Imprime o bloco para a saída padrão sem formatação.
void listarArquivo (int bloco)
Listar todo um arquivo que inicia no bloco X Parâmetro na linha de comando: -lb <numero do="" bloco>=""> Imprime o bloco para a saída padrão sem formatação.
Private Attributes
Parser * parser
Fat * FAT
Detailed Description
Contem os metodos para analisar as particoes FAT12.
Author:
Pargles
Abilio
Definition at line 15 of file FatAnalyser.h.
Constructor & Destructor Documentation
FatAnalyser::FatAnalyser (Parser * parse)
Inicializa os atributos da classe FatAnalyser com valores default.
Parameters:
Parser (contendo os argumentos selecionados)
Author:
Pargles
Abilio
Definition at line 11 of file FatAnalyser.cpp.
References FAT, Parser::getEnderecoSistemaArquivos(), and parser.
Member Function Documentation
void FatAnalyser::imprimiListaDeBlocosLivres () [private]
1.2 Imprimir lista de blocos livres Imprime os índices de todos os blocos que estão livres (ou seja, não são apontados pela FAT) em uma única linha.
Author:
Pargles
Abilio
Definition at line 67 of file FatAnalyser.cpp.
References FAT, and Fat::listarBlocosLivres().
Referenced by run().
void FatAnalyser::imprimirListaDeBlocosComDados () [private]
1.3 Imprimir lista de blocos livres com dados Imprime os índices de todos os blocos que estão livres e que tem conteúdo diferente de zeros, em uma única linha.
Author:
Pargles
Abilio
Definition at line 79 of file FatAnalyser.cpp.
References FAT, and Fat::listarBlocosLivresComDados().
Referenced by run().
void FatAnalyser::lerBloco (int bloco) [private]
1.4 Ler um determinado bloco Parâmetro na linha de comando: -lb <numero do="" bloco>=""> Imprime o bloco para a saída padrão sem formatação.
Parameters:
int (posicao do bloco a ser lido)
Author:
Pargles
Abilio
Definition at line 93 of file FatAnalyser.cpp.
References FAT, and Fat::listarBloco().
Referenced by run().
void FatAnalyser::listarArquivo (int bloco) [private]
Listar todo um arquivo que inicia no bloco X Parâmetro na linha de comando: -lb <numero do="" bloco>=""> Imprime o bloco para a saída padrão sem formatação.
Parameters:
int posicao inicial do bloco a ser listado
Author:
Pargles
Abilio
Definition at line 107 of file FatAnalyser.cpp.
References FAT, and Fat::imprimirArquivoCompleto().
Referenced by run().
void FatAnalyser::run ()
Executa o analisador de fat.
Author:
Pargles
Abilio
Definition at line 22 of file FatAnalyser.cpp.
References Parser::blocoComDados(), Parser::blocosLivres(), FAT, Fat::fecharReader(), Parser::getNumeroBlocoArquivo(), Parser::getNumeroDoBloco(), imprimiListaDeBlocosLivres(), imprimirListaDeBlocosComDados(), Fat::inserirEntradasFat(), lerBloco(), Parser::lerBloco(), listarArquivo(), Parser::listarArquivo(), Parser::listarInformacoes(), Fat::listarInformacoesCabecalho(), Fat::listarTabelaDiretorios(), Parser::listarTabelaDiretorios(), parser, Parser::verificaFats(), and verificarParticoesFat().
Referenced by main().
void FatAnalyser::verificarParticoesFat () [private]
1.1 Verificar FATs Verificar se as duas FATs são iguais – caso não sejam, imprimir uma lista de diferenças no seguinte formato, com uma linha para cada diferença:
Author:
Pargles
Abilio
Definition at line 54 of file FatAnalyser.cpp.
References Fat::diferenciarFATs(), and FAT.
Referenced by run().
Member Data Documentation
Fat* FatAnalyser::FAT [private]
Definition at line 18 of file FatAnalyser.h.
Referenced by FatAnalyser(), imprimiListaDeBlocosLivres(), imprimirListaDeBlocosComDados(), lerBloco(), listarArquivo(), run(), and verificarParticoesFat().
Parser* FatAnalyser::parser [private]
Definition at line 17 of file FatAnalyser.h.
Referenced by FatAnalyser(), and run().
The documentation for this class was generated from the following files:
inc/FatAnalyser.h
src/FatAnalyser.cpp