trab2_abilio_pargles: Parser Class Reference
Parser Class Reference
Responsável por separar os parametros que vao ser informados quando o programa for chamado.
#include <Parser.h>
Public Member Functions
Parser ()
Inicializa o Parser com valores default.
bool verificaFats ()
Retorna true se é para verificar as duas fats.
bool blocosLivres ()
Retorna true se é para listar os blocos livres.
bool blocoComDados ()
Retorna true se é para listar os blocos que contem dados.
bool lerBloco ()
Retorna true se é para ler um determinado bloco.
bool listarArquivo ()
Retorna true se é para listar um arquivo.
bool listarInformacoes ()
Retorna true se é para listar as informacoes do sistema de arquivos.
bool listarTabelaDiretorios ()
Retorna true se é para listar a tabela de diretorios.
int getNumeroDoBloco ()
Retorna o numero do bloco a ser lido.
int getNumeroBlocoArquivo ()
Retorna o numero do bloco inicial de um arquivo a ser listado.
string getEnderecoSistemaArquivos ()
Retorna o endereco do sistema de arquivos.
void setNumeroDoBloco (int numeroBloco)
Seta o numero do bloco a ser listado.
void setEnderecoSistemaArquivos (string Particao)
Seta o endereco onde se localiza o sistema de arquivos.
void parse (vector< string > Arguments)
Analiza os argumentos passados na chamada do programa e seta os valores passados por eles.
Private Attributes
bool vf
bool bl
bool bd
bool lb
bool la
bool inf
bool tab
int numeroBloco
int numeroBlocoArquivo
string enderecoSistemaArquivos
Detailed Description
Responsável por separar os parametros que vao ser informados quando o programa for chamado.
Author:
Pargles
Abilio
Definition at line 16 of file Parser.h.
Constructor & Destructor Documentation
Parser::Parser ()
Inicializa o Parser com valores default.
Author:
Pargles
Abilio
Definition at line 9 of file Parser.cpp.
References bd, bl, inf, la, lb, numeroBloco, numeroBlocoArquivo, tab, and vf.
Member Function Documentation
bool Parser::blocoComDados ()
Retorna true se é para listar os blocos que contem dados.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 50 of file Parser.cpp.
References bd.
Referenced by printaItensSelecionados(), and FatAnalyser::run().
bool Parser::blocosLivres ()
Retorna true se é para listar os blocos livres.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 39 of file Parser.cpp.
References bl.
Referenced by printaItensSelecionados(), and FatAnalyser::run().
string Parser::getEnderecoSistemaArquivos ()
Retorna o endereco do sistema de arquivos.
Returns:
string (Particao A)
Author:
Pargles
Abilio
Definition at line 128 of file Parser.cpp.
References enderecoSistemaArquivos.
Referenced by FatAnalyser::FatAnalyser().
int Parser::getNumeroBlocoArquivo ()
Retorna o numero do bloco inicial de um arquivo a ser listado.
Returns:
int
Author:
Pargles
Abilio
Definition at line 117 of file Parser.cpp.
References numeroBlocoArquivo.
Referenced by FatAnalyser::run().
int Parser::getNumeroDoBloco ()
Retorna o numero do bloco a ser lido.
Returns:
int
Author:
Pargles
Abilio
Definition at line 106 of file Parser.cpp.
References numeroBloco.
Referenced by printaItensSelecionados(), and FatAnalyser::run().
bool Parser::lerBloco ()
Retorna true se é para ler um determinado bloco.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 61 of file Parser.cpp.
References lb.
Referenced by printaItensSelecionados(), and FatAnalyser::run().
bool Parser::listarArquivo ()
Retorna true se é para listar um arquivo.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 72 of file Parser.cpp.
References la.
Referenced by FatAnalyser::run().
bool Parser::listarInformacoes ()
Retorna true se é para listar as informacoes do sistema de arquivos.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 84 of file Parser.cpp.
References inf.
Referenced by FatAnalyser::run().
bool Parser::listarTabelaDiretorios ()
Retorna true se é para listar a tabela de diretorios.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 95 of file Parser.cpp.
References tab.
Referenced by FatAnalyser::run().
void Parser::parse (vector< string > Arguments)
Analiza os argumentos passados na chamada do programa e seta os valores passados por eles.
Parameters:
vector<string> Arguments (Lista dos argumentos passados na chamada do programa)
Author:
Pargles
Abilio
Definition at line 161 of file Parser.cpp.
References bd, bl, inf, la, lb, numeroBloco, numeroBlocoArquivo, setEnderecoSistemaArquivos(), tab, and vf.
Referenced by main().
void Parser::setEnderecoSistemaArquivos (string Particao)
Seta o endereco onde se localiza o sistema de arquivos.
Parameters:
string particao
Author:
Pargles
Abilio
Definition at line 150 of file Parser.cpp.
References enderecoSistemaArquivos.
Referenced by parse().
void Parser::setNumeroDoBloco (int numeroDoBloco)
Seta o numero do bloco a ser listado.
Parameters:
int (numero do bloco)
Author:
Pargles
Abilio
Definition at line 139 of file Parser.cpp.
References numeroBloco.
bool Parser::verificaFats ()
Retorna true se é para verificar as duas fats.
Returns:
bool
Author:
Pargles
Abilio
Definition at line 28 of file Parser.cpp.
References vf.
Referenced by printaItensSelecionados(), and FatAnalyser::run().
Member Data Documentation
bool Parser::bd [private]
Definition at line 21 of file Parser.h.
Referenced by blocoComDados(), parse(), and Parser().
bool Parser::bl [private]
Definition at line 20 of file Parser.h.
Referenced by blocosLivres(), parse(), and Parser().
string Parser::enderecoSistemaArquivos [private]
Definition at line 28 of file Parser.h.
Referenced by getEnderecoSistemaArquivos(), and setEnderecoSistemaArquivos().
bool Parser::inf [private]
Definition at line 24 of file Parser.h.
Referenced by listarInformacoes(), parse(), and Parser().
bool Parser::la [private]
Definition at line 23 of file Parser.h.
Referenced by listarArquivo(), parse(), and Parser().
bool Parser::lb [private]
Definition at line 22 of file Parser.h.
Referenced by lerBloco(), parse(), and Parser().
int Parser::numeroBloco [private]
Definition at line 26 of file Parser.h.
Referenced by getNumeroDoBloco(), parse(), Parser(), and setNumeroDoBloco().
int Parser::numeroBlocoArquivo [private]
Definition at line 27 of file Parser.h.
Referenced by getNumeroBlocoArquivo(), parse(), and Parser().
bool Parser::tab [private]
Definition at line 25 of file Parser.h.
Referenced by listarTabelaDiretorios(), parse(), and Parser().
bool Parser::vf [private]
Definition at line 19 of file Parser.h.
Referenced by parse(), Parser(), and verificaFats().
The documentation for this class was generated from the following files:
inc/Parser.h
src/Parser.cpp