trab2_abilio_pargles: src/testeme.cpp File Reference
src/testeme.cpp File Reference
#include "../inc/Parser.h"
#include "../inc/FatAnalyser.h"
#include <iostream>
Functions
void printaItensSelecionados (Parser *argumentos)
Imprime os itens selecionados na passagem do argumento.
int main (int argc, char *argv[])
Inicializa o funcionamento do programa Faz a leitura dos argumentos e a passagem deste para o parser.
Function Documentation
int main (int argc, char * argv[])
Inicializa o funcionamento do programa Faz a leitura dos argumentos e a passagem deste para o parser.
Parameters:
Argumento da linha de comando
Author:
Pargles
Abilio
Definition at line 97 of file testeme.cpp.
References Parser::parse(), and FatAnalyser::run().
void printaItensSelecionados (Parser * argumentos)
Imprime os itens selecionados na passagem do argumento.
Parameters:
Parser contendo os argumentos selecionados
Author:
Pargles
Abilio
Definition at line 64 of file testeme.cpp.
References Parser::blocoComDados(), Parser::blocosLivres(), Parser::getNumeroDoBloco(), Parser::lerBloco(), and Parser::verificaFats().